### ISSUE TITLE
Ensure the customLocale plugin is registered before the other plugins

### ISSUE THREAD

**Issue by jonasraoni** [pkp/customLocale#18]
I saw the method below on the `defaultTranslation` plugin, and I think it makes sense to have it on this plugin as well, in order to ensure it's loaded/registered before other plugins:
https://github.com/pkp/defaultTranslation/blob/425fee0880efc7782196b3e8e8e68aab9bdf3ca5/DefaultTranslationPlugin.php#L60-L66

PRs
- `main`
- https://github.com/pkp/customLocale/pull/19
- `stable-3_3_0`
- https://github.com/pkp/customLocale/pull/20

**Comment by jonasraoni** [comment]
@asmecher

PRs
- `main`
- https://github.com/pkp/customLocale/pull/19
- `stable-3_3_0`
- https://github.com/pkp/customLocale/pull/20

**Comment by asmecher** [comment]
Merged the stable branch PR, but the main branch tests are failing.

**Comment by jonasraoni** [comment]
@asmecher I just fixed the tests for the `main` branch.

**Comment by jonasraoni** [comment]
@asmecher just a post new year ping 😁

**Comment by asmecher** [comment]
Merged the main branch; closing!
