### ISSUE TITLE
Improve ability to edit languages other than the primary locale

### ISSUE THREAD

**Issue by asmecher** [pkp/customLocale#8]
Currently the custom locale plugin only allows editing of the journal's primary locale. For users with other locales, it's necessary to work around this by temporarily setting the primary locale to the other locale.

Improve the plugin's ability to work with other languages without requiring the work-around.

**Comment by asmecher** [comment]
Merged to `stable-3_2_1` and `main`, but awaiting confirmation from e.g. https://forum.pkp.sfu.ca/t/custom-locale-plugin-doesnt-react-to-primary-locale-change/66189/3 before closing the issue and building a new release package.

**Comment by jonasraoni** [comment]
@asmecher It's working fine for me, I think this issue can be closed =]

**Comment by asmecher** [comment]
OK, thanks!
